---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    mengtongun.com/app: redis
    mengtongun.com/stack: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      mengtongun.com/app: redis
  template:
    metadata:
      labels:
        mengtongun.com/app: redis
    spec:
      restartPolicy: Always
      containers:
      - name: redis
        image: bitnami/redis:latest
        envFrom:
        - secretRef:
            name: redis-secret
