---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    mengtongun.com/app: api
    mengtongun.com/stack: backend
spec:
  type: ClusterIP
  selector:
    mengtongun.com/app: api
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
