---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    mengtongun.com/app: postgres
    mengtongun.com/stack: backend
stringData:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: dbpass
