---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    mengtongun.com/app: postgres
    mengtongun.com/stack: backend
data:
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  POSTGRES_DB: app
