---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: admin-auth
  labels:
    mengtongun.com/app: traefik
    mengtongun.com/stack: traefik
spec:
  basicAuth:
    secret: auth-secret
