---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  labels:
    mengtongun.com/app: traefik
    mengtongun.com/stack: traefik
  annotations:
    mengtongun.com/load-balancer: traefik
spec:
  type: NodePort
  selector:
    mengtongun.com/app: traefik
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
      name: web
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
      name: websecure
